name: flutter_call_ui
version: 0.2.0
homepage: github.com/muhammedkpln
description: Backend agnostic call ui for Flutter.
environment: 
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter_webrtc: ^0.9.7
  intl: ^0.17.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: null
